// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCNHbGpXHzGZqfRiz7x7iXQdbHucv6PRxc',
    appId: '1:733902188694:web:9de30c41b382678aadd2b7',
    messagingSenderId: '733902188694',
    projectId: 'cis-game-fe7ae',
    authDomain: 'cis-game-fe7ae.firebaseapp.com',
    storageBucket: 'cis-game-fe7ae.appspot.com',
    measurementId: 'G-HSXG3V60WB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB9WYi70pwRMpgu35azHbjwyGjtCMtrfSM',
    appId: '1:733902188694:android:7cc107c090dd13b5add2b7',
    messagingSenderId: '733902188694',
    projectId: 'cis-game-fe7ae',
    storageBucket: 'cis-game-fe7ae.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA5zfPSW_c7czkylgemoKp_s2WqX96AoZI',
    appId: '1:733902188694:ios:b85175b0934915cbadd2b7',
    messagingSenderId: '733902188694',
    projectId: 'cis-game-fe7ae',
    storageBucket: 'cis-game-fe7ae.appspot.com',
    iosBundleId: 'com.example.cisGame',
  );
}
